### ISSUE TITLE
support inline callbacks, via txaio.inline_callbacks

### ISSUE THREAD

**Issue by graingert** [crossbario/txaio#110]
eg: https://github.com/mikeal/deferred/blob/master/deferred/_defer.py#L796-L804

```python
import txaio
txaio.use_twisted()  # or .use_asyncio()

f0 = txaio.create_future()
f1 = txaio.as_future(some_func, 1, 2, key='word')

@txaio.inline_callbacks
def wait_for():
    v0 = yield f0
    v1 = yield v1

    txaio.return(v0 + v1)


# ...
txaio.resolve(f0, "value")
txaio.reject(f1, RuntimeError("it failed"))
```

similar to https://github.com/crossbario/txaio/issues/62 except this would be an explicit implementation inside txaio.

**Comment by graingert** [comment]
> I was just thinking that there might be some way for txaio to make plain yield in Python3 behave like yield from as far as Futures are concerned -- but, I haven't explored that at all and it very well could be impossible. And then, yes, there's also the async syntax that obviously also can't be magically made to appear in Python2 ;)

Yes inlineCallbacks from twisted works exactly like this.

**Comment by meejah** [comment]
So, the issue here is there needs to be *one* syntax to use against txaio which must be plain `yield` since that's all Py2 will support (i.e. can't use `yield from` nor `await`).

You'd need a story to make `yield f` work inside `@txaio.coroutine` (or whatever name) on all platforms that txaio supports (i.e. Py2, Py3, PyPy with either Twisted or asyncio). I think you're proposing an implementation inside txaio that does that? If you can support all the platforms I don't see why we couldn't include this in txaio...

If you can keep the "await" code in some "only in asyncio or Twisted on Py3" area, then it might be possible to make it work ... perhaps `ensureDeferred` from Twisted can provide some inspiration.

**Comment by graingert** [comment]
> If you can keep the "await" code in some "only in asyncio or Twisted on Py3" area, then it might be possible to make it work ... perhaps ensureDeferred from Twisted can provide some inspiration.

I'd probably avoid using await at all inside `txaio`

**Comment by meejah** [comment]
Oh, hmm, looking at `ensureDeferred` in Twisted I guess an `async def`-d method just literally returns a generator, so "await" is *exactly* just syntax-sugar and you can `.send()` it and get things back out. I haven't really played with this at this level -- does it return `Future` instances back out? Anyway -- in this case it could probably work without introducing possible syntax errors :)

**Comment by graingert** [comment]
> does it return `Future` instances back out

No it returns a coroutine

**Comment by graingert** [comment]
@meejah but you can call [`__await__()`](https://docs.python.org/3/reference/datamodel.html#object.__await__) to get an iterator.

**Comment by graingert** [comment]
txaio and twisted are python 3 only
