### ISSUE TITLE
Tie into default logging if start_logging() is never called

### ISSUE THREAD

**Issue by meejah** [crossbario/txaio#54]
See https://github.com/crossbario/autobahn-python/issues/596

We *should* be able to tie into Python's internal logging system properly even in the case when ``txaio.start_logging()`` isn't ever called.

**Comment by oberstet** [comment]
Could you have a quick look at https://github.com/crossbario/autobahn-python/issues/594? Because I do call into `txaio.start_logging` [there](https://github.com/crossbario/autobahn-python/blob/master/examples/asyncio/websocket/testee/testee_server.py#L111), but I still get no log output somehow. Maybe I am doing something wrong still?

**Comment by meejah** [comment]
I actually think I found and fixed that right here https://github.com/crossbario/txaio/pull/55/files#diff-1ffabb82a1cbddd262638773a68ee68bR132

**Comment by meejah** [comment]
Apparently there was still an off-by-one in the logging-level stuff :/

Okay, I double-checked and yes this I think was the problem you saw above.

**Comment by meejah** [comment]
So, needs https://github.com/crossbario/txaio/pull/55 to fix

**Comment by oberstet** [comment]
merged
