### ISSUE TITLE
as_future and generators

### ISSUE THREAD

**Issue by Paranaix** [crossbario/txaio#56]
Both twisted and asyncio come with decorators which allow to write async code as if synchronous (`@inlineCallbacks` and `@coroutine` for reference). However it's easy to forget these decorators either while writing code or while refactoring code (e.g switching from a synchronous implementation of a func to async).

I argue that in 90% of all cases where a function returning a generator is passed into `as_future` the user actually just forgot the decorator. This can lead to nasty and hard to debug behaviour. E.g Autobahn's `ApplicationSession.onJoin` handler will simply not be invoked at all, but at the same time there isn't any feedback about this as well. The application will just continue as usual although code which was intended to be executed, was not. Due to the dynamic nature of Python, this can mean that actual errors might happen much much later. Cause and effect might not be that obvious to identify due to them being seperated by a very long period of time.

I propose that returning a generator from a function which is passed into `as_future` is to be considered an error. For the case that one actually wants to return a generator, the function should be decorated with `@txaio.returns_gen` which will wrap the generator in a `_Generator` marker object telling the `as_future` implementation, that returning a generator was actually intented.

I'm aware of the fact that this is not consistent in behaviour with e.g `maybeDeferred` but I believe this the right place to implement that check. Otherwise it would mean that every piece of code which would need such a check would have to do it on its own which is just as easy to forget. Also this adds alot of boilerplate everytime.

**Comment by meejah** [comment]
*Ideally* txaio could/would provide a decorator that acts like (or just "is") ``@coroutine/@inlineCallbacks`` -- however, we don't need or use this feature in Autobahn libraries, and so it doesn't exist ;)

That said, though, would the above test actually work for ``asyncio`` at all? Some quick tests indicate that *any* function decorated with @coroutine returns a generator-object (whether it includes a ``yield`` or ``yield from`` or not). It seems that even ``asyncio.iscoroutine`` is confused: a simple function like ``def foo(): yield "bar"`` causes ``asyncio.iscoroutine()`` to return True...

The issue with implementing this for the Twisted side is that right now we *just* call ``maybeDeferred``, but in order to implement this feature-request I *think* we'd basically have to replicate maybeDeferred in txaio -- unless there's a way to test if a function is a generator-function *before* invoking it...? I wonder if Twisted people would be open to considering a generator-producing function given to maybeDeferred as an error...?

So: in principle I agree that a "bare" generator-function is *almost certainly* not what you wanted to give to ``txaio.as_future``. But, how to implement this cleanly?

I'm also curious: what are you using txaio for?

**Comment by Paranaix** [comment]
I'm not directly using txaio. As mentioned, Autobahn's `ApplicationSession.onJoin` will currently not log an error if a generator is returned, but won't execute anything as well. I'm sure there will be many more places with similiar behaviour. Instead of checking this on every single occasion, I think the best solution would be to directly solve this in `txaio.as_future` even if this means some small syntactic inconveniences for those very rare cases were generators are actually expected as results.

So first regarding asyncio: We solely work with twisted so I'm not really an expert on this area. Although while I could replicate your described behaviour of `iscoroutine()`, I noticed that `iscoroutinefunction()` is able to differentiate just fine between:

```
def test(): # will return False
    yield 1

@asyncio.coroutine
def test2(): # will return True
    yield 2
```

Now regarding twisted: I don't even think that it is required to replace `maybeDeferred`, a crude implementation of `as_future` could be as simple as:

```
def as_future(func, *args, **kwargs):
    d = maybeDeferred(func, *args, **kwargs)
    if d.called:
        def cb(result):
            if isinstance(result, _GeneratorWrapper):
                return result.gen

            if inspect.isgenerator(result):
                raise Exception("function returned a generator. Did you forget to decorate your function with @inlineCallbacks?")

            return result

        d.addCallback(cb)

    return d
```

**Comment by meejah** [comment]
Well, currently the function is just ``return maybeDeferred(func, *args, **kw)`` ;) and txaio tries really, really hard not to do any "wrapping" etc (as there are typically a *lot* of Deferreds/Futures produced). Also, this has kind of "magical" downstream effects on users-of-users of ``txaio`` -- even if that case is super rare.

What about a separate API for this? Perhaps it's even possible to implement it as a helper-style function. Since the actual use-case is to issue a nicer error when an Autobahn ApplicationSession subclass implements ``onJoin`` (etc) incorrectly, it's really up to the user of txaio to decide when they want these semantics should apply.

So, e.g., ``txaio.error_if_generator(instance.some_method)`` or something would raise when:

 * using twisted and ``some_method`` is a generator-function but not ``@inlineCallbacks``-decorated
 * using asyncio and ``some_method`` is a generator-function but not ``@coroutine``-decorated

Then, this could be used in e.g. Autobahn to detect if user-methods are "just" bare generators. Thus, Autobahn could choose to either provide a "way out" (e.g. decorator) or simply declare "you cannot use a method that produces a generator for ``onJoin``, etc."

**Comment by Paranaix** [comment]
Well that's a decision to be made. I think that having this check in `as_future` is appropriate due to two reasons:

1. In 90% of all usecases, this check is probably desired. It's as easy to forget a call to `error_if_generator` as it is to forget to decorate a function with `@inlineCallbacks`.

2. For those remaining 10% the code will fail pre-emptively, directly causing the user to receive an error message which could also contain a line like _"If returning a generator was desired, decorate your function with @txaio.returns_gen"_.

But yeah, a `error_if_generator` function is definitely another option.

**Comment by meejah** [comment]
Regarding forgetting ``error_if_generator`` or whatever, no that's up to the *library* authors (e.g. Autobahn) -- users (of the library) wouldn't need to remember that. This lets library authors decide which Deferred-returning functions are "special" (e.g. user-facing) instead of just "mysteriously" affecting every Deferred produced by anything using ``txaio``.

As to the technical aspects, I think it's possible: we can detect a "bare" generator function with ``inspect.isgeneratorfunction``, which will return ``False`` after decoration with ``@inlineCallbacks``. This will return ``True`` for ``@asyncio.coroutine``, but we can detect an asyncio coroutine with ``asyncio.iscoroutinefunction``.

Is there an autobahn feature-bug for "complain if ``onJoin`` is a bare generator-function"? I couldn't find one.

**Comment by oberstet** [comment]
@Paranaix I can see you itch, but `txaio` deliberately implements a minimal, "no magic" wrapper. This is totally by design - and I think it's the only sane and practical way of achieving txaio goals. Also, AutobahnPython does not use co-routines internally - this is necessary for source compatibility across Python 2 and 3.

> Is there an autobahn feature-bug for "complain if onJoin is a bare generator-function"? I couldn't find one.

Yep, I agree with @meejah : that would be a better place to discuss and possibly address this issue.

**Comment by Paranaix** [comment]
> Regarding forgetting error_if_generator or whatever, no that's up to the library authors (e.g. Autobahn) -- users (of the library) wouldn't need to remember that. This lets library authors decide which Deferred-returning functions are "special" (e.g. user-facing) instead of just "mysteriously" affecting every Deferred produced by anything using txaio.

Yes indeed, but just remember all those issues with logging in crossbar and autobahn (this also being one btw). Library authors after all are also just human beings. My point on this is, that we should design for the most common case and make the least common an exception, not vice versa.

I haven't opened an issue in Autobahn yet, because I believe this should be solved in one common spot, namely txaio. Otherwise I would have to create issues for any other user-defined async method used by autobahn as well.

I can understand your ressentiment against solving this in `as_future` but then txaio should atleast provide an easy to use `error_if_generator` function. This is not something only Autobahn needs but almost any code dealing with twisted or asyncio, the only exception being functions which actually expect a future/deferred to return a generator, which clearly make up the minority.

**Comment by meejah** [comment]
I guess I'm getting at: if txaio is the right "central spot" to do a change like this, why not ``maybeDeferred`` in Twisted itself? That is, if there are good arguments to make people who want their Deferred to return a real generator "do something special", perhaps those arguments can convince Twisted :)

In any case, let's move further discussion to https://github.com/crossbario/autobahn-python/issues/610 -- if there's a use-case we can implement here if that ends up making the most sense.
