### ISSUE TITLE
Explain why co-routine style is unsupported

### ISSUE THREAD

**Issue by Stibbons** [crossbario/txaio#70]
This is really important if we want to use txaio that decorators to be supported.

Thanks

**Comment by oberstet** [comment]
This explicitly unsupported as it doesn't make sense. Please see the docs

**Comment by oberstet** [comment]
This is explicitly unsupported. See the docs. To maintain cross Python version and cross framework agnostic coding, you cannot use decorators or coroutines.

This is really important if we want to use txaio that decorators to be supported.

Thanks

**Comment by Stibbons** [comment]
yes, I know. But without these we go 5 year backward, and this remove almost any reason to use txaio :(

**Comment by oberstet** [comment]
No, it doesn't: read the docs. Anyway: you cannot (= technically _impossible_) write code using co-routines that will run on Python 2 and 3, and Twisted and asyncio.

**Comment by meejah** [comment]
txaio makes it *possible* to write a cross-platform py2/pypy/py3/asyncio/twisted codebase -- this makes the library itself easier to use *for users*. The price the implementor of the library pays is the inconvenience of a "lowest common denominator" API. 

But, seriously: if you have concrete ideas on how to make a decorator work I'd be curious to see some proof-of-concept code :)

**Comment by oberstet** [comment]
`yield from` is invalid syntax on Python 2. `await` / `async` is invalid syntax on Python < 3.5. and so ..

**Comment by oberstet** [comment]
Another aspect that might be worth mentioned (or do we already): the main use case of `txaio` is **library authors**, _not_ **application developers**. Again, the reason is, that due to the (technically unavoidable) restrictions (under the goal of source compat.), and regular app developers will be disappointed likely.

The latest shit in the Python community is `async` / `await` - which, granted, is nice syntax - but Python 3.5+ only. So, I'd say, we should clearly point app developers to Python 3.5+ .. and scare away from using `txaio` directly.

Of course, Autobahn and Crossbar.io have different goals / requirements:

1. Autobahn absolutely must run on various combinations of Python version and network framework. And hence, we bite the bullet and refrain from using co-routine style altogether (within the library)
2. Crossbar.io is Twisted only, and hence _can_ use co-routines, because the syntax for Twisted co-routines is the same for Python 2.7 and Python 3.3+ (including 3.5+ - which are the Python versions Crossbar.io can run on top)

> I also think, above also hints at the following: we probably should discourage writing Python app components to be run in Crossbar.io side-by-side (embedded in router workers) or container workers. Because that will essentially impose Twisted. Instead, we should recommend writing (new) Python components in Python 3.5+ (in asyncio) and running as guest workers. However, this is a separate issue - and would need discussion ...

**Comment by Stibbons** [comment]
While I agree on the yield from syntax, I think it should be still possible to write an equivalent of defer.inlineCallbacks and still be compatible with all your requirements. Because from what I see from your api, this is mainly callback/errback chain, which translate pretty well in inlinecb.

To be short: "lowest common denominator" API => inlineCallbacks-like API, so with ``yield`` and not ``yield from``.

If I find time to work on it I'll be happy to see what I can do

**Comment by meejah** [comment]
Yes, for sure nothing will work with ``awat/async`` nor ``yield from``.

If you do make something work please open a new PR/issue.

**Comment by oberstet** [comment]
@Stibbons Well. I don't know what to say;) Go waste your time? asyncio on Python 3 requires the `yield from` syntax. `txaio` is _not_ a wrapping library - it (by design) exposes the native stuff. And the native co-routines vastly differ. Anyway.

@meejah As can be seen from this discussion, we need it in the docs;)

**Comment by oberstet** [comment]
For the fun (and because I wanted to try it some time;), here is a Twitter poll on "What coro style do you prefer?"

https://twitter.com/oberstet/status/724705121037369344

**Comment by oberstet** [comment]
This is explained in the docs now
