### ISSUE TITLE
txaio-2.5.1 fails tests at the distro level

### ISSUE THREAD

**Issue by dol-sen** [crossbario/txaio#77]
The test/test_packaging.py file should not be included as part of the normal release tarballs.
On Gentoo I have had to rm the file to prevent test failures as part of the install process when FEATURES=test is enabled.  This test is obviously for developing the code only.   Not for testing the code itself.  The failure was due to the sandbox and multiple python install/test capabilities in Gentoo.  I did not delve deeply into the failure, but it was obviously a path issue due to the sandbox.

All other tests passed once I removed that test.

**Comment by meejah** [comment]
Well, arguably it *is* for testing some of the code: it (tries to) ensure that "whatever is produced" from `python setup.py sdist` will actually be installable by `python -m pip install ..`. This was added due to a release where that wasn't actually true (and hence broke installs from PyPI).

Is it just the hard-coded `../dist/` path that's breaking it (i.e. maybe `python setup.py sdist` accepts an option for where to put the tarball?) I don't use Gentoo, so am not in a good position to try it out for your case.

**Comment by dol-sen** [comment]
I didn't investigate the path problem.  It is likely that the working directory is not set correctly.   Everything is sandboxed, there are several directories, on where the source tarballs are unpacked/built/tested/....  In this case the sources are copied into new sub-directories for each python version it is being installed to where the tests are run.  Also we don't use pip to install in Gentoo, we actually discourage it's use, it is rather hazardous to the python ecosystem when run as root.  Gentoo can have multiple python versions simultaneously installed and used by various apps pip screws that system up overwriting things and points to itself.  I'll work on it some more in the next weeks.  It was a new dep for a dep that as bumped in buildbot which is my primary concern at this time.  I still have more code to migrate to the new version and APIs.

**Comment by oberstet** [comment]
I don't care about distro packaging bullshit.
